version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  heroku: circleci/heroku@1.2.2

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  heroku_deploy:
    jobs:
      - deploy
