version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            set -e

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            echo Using SSH Config Dir $SSH_CONFIG_DIR

            mkdir -p $SSH_CONFIG_DIR

            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==' >> $SSH_CONFIG_DIR/known_hosts
            
            (umask 077; touch $SSH_CONFIG_DIR/id_rsa)
            chmod 0600 $SSH_CONFIG_DIR/id_rsa
            (cat <<EOF > $SSH_CONFIG_DIR/id_rsa
            $CHECKOUT_KEY
            EOF
            )

            export GIT_SSH_COMMAND='ssh -i $SSH_CONFIG_DIR/id_rsa -o UserKnownHostsFile=$SSH_CONFIG_DIR/known_hosts'

            # use git+ssh instead of https
            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
            git config --global gc.auto 0 || true

            if [ -e /home/circleci/project/.git ]
            then
              cd /home/circleci/project
              git push https://heroku:f5336682-b2f4-4673-a225-fdef1c2921f0@git.heroku.com/cvds-lab-6.git master
            else
              mkdir -p /home/circleci/project
              cd /home/circleci/project
              git clone $CIRCLE_REPOSITORY_URL .
              git push https://heroku:f5336682-b2f4-4673-a225-fdef1c2921f0@git.heroku.com/cvds-lab-6.git master
            fi

workflows:
  build_test_deploy:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - deploy:
          requires:
            - maven/test # only run deploy-via-git job if the maven/test job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch
