version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            cd /home/circleci/project
            git push https://heroku:f5336682-b2f4-4673-a225-fdef1c2921f0@git.heroku.com/cvds-lab-6.git master

workflows:
  build_test_deploy:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - deploy:
          requires:
            - maven/test # only run deploy-via-git job if the maven/test job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch
